= Анализ задачи "Канадский кроссворд".
'''

Требуется разработать приложение, которое позволяет генерировать и разгадывать канадский кроссворд.
В канадском кроссворде слова пересекаются друг с другом всеми буквами.

Работу программы можно разделить на следующие стадии: +

. Ввод пользователем слов и их описаний.
. Ввод пользователем размера игрового поля.
. Генерация игрового поля из введенных слов.
. Вывод в консоль сгенерированного игрового поля и описаний/вопросов слов.
. Ввод пользователем слов в игровое поле (в формате "№ слова-слово").
. Перерисовка игрового поля с нововведенным словом.
. Проверка разгаданного кроссворда (скорее всего будет выполняться при нажатии определенной клавиши).
. Вывод результата проверки.

Программную реализацию структкрно можно разделить на 2 модуля: +

* Модуль пользовательского интерфейса;
* Модуль реализации логики.

Соответственно модуль пользовательского интерфейса будет отвечать за реализацию взаимодействия+
пользователя с программой через консоль (предполагается использовать библиотеку Lanterna).
В модуле реализации логики будет реализация основный функций приложения, связанных с созданием словаря,
генерацией игрового поля, проверкой правильности решения кроссворда.